name: Release
on:
  release:
    types: [published]
jobs:
  buildAppxBundle:
    name: Build AppInstaller and Bundle
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare Env
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Cache Packages
      id: nuget-cache
      uses: actions/cache@v2
      with:
        path: ~\.nuget\packages
        key: nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          nuget-
    - name: Restore Packages
      if: steps.nuget-cache.outputs.cache-hit != 'true'
      run: MSBuild LRReader.UWP\LRReader.UWP.csproj -t:restore -nologo -v:minimal
    - name: Build AppInstaller
      env:
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        CERT_GPG: ${{ secrets.CERT_GPG }}
        CERT_BASE64: ${{ secrets.CERT_BASE64 }}
      run: |
        [xml]$xmlDoc = Get-Content "./LRReader.UWP/Package.appxmanifest"
        Set-Content -NoNewline -Path "./version.txt" -Value $xmlDoc.Package.Identity.Version
        [IO.File]::WriteAllBytes("./Cert.pfx.gpg", [Convert]::FromBase64String("${env:CERT_BASE64}"))
        & "C:\Program Files\Git\usr\bin\gpg.exe" --quiet --batch --yes --decrypt --passphrase="${env:CERT_GPG}" --output Cert.pfx Cert.pfx.gpg
        MSBuild LRReader.UWP\LRReader.UWP.csproj -nologo -r -v:minimal /p:Configuration=Release /p:DefineConstants="TRACE;NETFX_CORE;WINDOWS_UWP;SIDELOAD" /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="" /p:PackageCertificateKeyFile="..\Cert.pfx" /p:PackageCertificatePassword="${env:CERT_PASSWORD}" /p:GenerateAppInstallerFile=True /p:AppInstallerUri="https://s3.guerra24.net/projects/lrr/$($xmlDoc.Package.Identity.Version)"
        Remove-Item -Path "./Cert.pfx.gpg","./Cert.pfx"
        Invoke-Expression "./Util/CleanInstaller.ps1"
    - name: Prepare for upload
      run: ./Util/PrepareForUpload.ps1
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LRReader
        path: LRReader.UWP/AppPackages
    - name: Upload Version
      uses: actions/upload-artifact@v2
      with:
        name: Version
        path: version.txt
    - name: Upload to Release
      uses: Shopify/upload-to-release@master
      with:
        name: LRReader.appinstaller
        path: LRReader.UWP/AppPackages/LRReader.UWP.appinstaller
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  uploadToS3:
    name: Upload Release
    needs: buildAppxBundle
    runs-on: ubuntu-18.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: LRReader
          path: AppPackages
      - name: Download Version
        uses: actions/download-artifact@v2
        with:
          name: Version
      - name: Setup Envs
        run: echo "DEST_DIR=projects/lrr/$(cat version.txt)" >> $GITHUB_ENV
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "AppPackages"