name: Release Delivery
on: [push]
jobs:
  buildAppxBundle:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build AppxBundle
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" LRReader\LRReader.csproj -p:Configuration=Debug;AppxBundle=Always
