name: Continuous Delivery
on: push
jobs:
  buildAppxBundle:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build AppxBundle
      env:
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        CERT_GPG: ${{ secrets.CERT_GPG }}
      run: |
        "C:\Program Files\Git\usr\bin\gpg.exe" --quiet --batch --yes --decrypt --passphrase="%CERT_GPG%" --output Cert.pfx Util\Cert.pfx.gpg
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" LRReader.UWP\LRReader.UWP.csproj -nologo -r -v:minimal -p:Configuration=Debug;AppxBundlePlatforms="x86|x64";AppxPackageSigningEnabled=true;PackageCertificateThumbprint="";PackageCertificateKeyFile="..\Cert.pfx";PackageCertificatePassword="%CERT_PASSWORD%"
      shell: cmd
    - name: Copy scripts
      run: copy "Util\Install App.ps1" "LRReader.UWP\AppPackages\"
      shell: cmd
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: LRReader
        path: LRReader.UWP/AppPackages