name: Release Delivery
on: 
  push:
    branches:
    - develop
jobs:
  buildAppxBundle:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build AppInstaller
      env:
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        CERT_GPG: ${{ secrets.CERT_GPG }}
      run: |
        "C:\Program Files\Git\usr\bin\gpg.exe" --quiet --batch --yes --decrypt --passphrase="%CERT_GPG%" --output Cert.pfx Util\Cert.pfx.gpg
        "powershell" "& .\Util\Version.ps1"
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" LRReader.UWP\LRReader.UWP.csproj -nologo -r -v:minimal -p:Configuration=Release;AppxPackageSigningEnabled=true;PackageCertificateThumbprint="";PackageCertificateKeyFile="..\Cert.pfx";PackageCertificatePassword="%CERT_PASSWORD%";GenerateAppInstallerFile=True;AppInstallerUri="https://s3.guerra24.net/projects/lrr/deploy/updates"
      shell: cmd
    - name: Copy scripts
      run: copy "Util\Install App.ps1" "LRReader.UWP\AppPackages\"
      shell: cmd
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: LRReader
        path: LRReader.UWP/AppPackages