name: Release Delivery
on:
  release:
    types: [published]
jobs:
  buildAppxBundle:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build AppxBundle
      env:
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        CERT_GPG: ${{ secrets.CERT_GPG }}
      run: |
        "C:\Program Files\Git\usr\bin\gpg.exe" --quiet --batch --yes --decrypt --passphrase="%CERT_GPG%" --output Cert.pfx Util\Cert.pfx.gpg
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" LRReader.UWP\LRReader.UWP.csproj -nologo -r -v:minimal -p:Configuration=Release;AppxPackageSigningEnabled=true;PackageCertificateThumbprint="";PackageCertificateKeyFile="..\Cert.pfx";PackageCertificatePassword="%CERT_PASSWORD%"
      shell: cmd
    - name: Copy scripts
      run: copy "Util\Install App.ps1" "LRReader.UWP\AppPackages\"
      shell: cmd
    - name: Zip Bundle for Release
      run: |
        mkdir Artifacts
        "C:\Program Files\7-Zip\7z.exe" a -r -tzip -mm=LZMA -mmt=on -mx=7 Artifacts/LRReader.zip ./LRReader.UWP/AppPackages/*
      shell: cmd
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: LRReader
        path: LRReader.UWP/AppPackages
    - name: Upload to Release
      uses: Shopify/upload-to-release@master
      with:
        name: LRReader.zip
        path: Artifacts/LRReader.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}